# Generated by Django 3.2.16 on 2022-12-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора книги', to='catalog.Autor', verbose_name='Aвтop книги'),
        ),
    ]
